stages:
  - test
  - release

cache:
  paths:
    - node_modules/
    - ${HOME}/.cache/yarn

.common: &common
  except:
    - tags
  stage: test

.node_6: &node_6
  image: node:6

.node_8: &node_8
  image: node:8

.node_next: &node_next
  image: node:latest
  allow_failure: true

.yarn: &yarn
  script:
    - source ${HOME}/.bashrc
    - yarn install --frozen-lockfile && yarn test && ($(yarn bin)/codecov || echo "Codecov did not collect coverage reports")

.yarn_latest: &yarn_latest
  <<: [*yarn]
  before_script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash

node_6_yarn_latest:
  <<: [*common, *node_6, *yarn_latest]

node_8_yarn_latest:
  <<: [*common, *node_8, *yarn_latest]

node_next_yarn_latest:
  <<: [*common, *node_next, *yarn_latest]

release:
  <<: [*node_8]
  before_script:
    - yarn install --frozen-lockfile
  only:
    - master@hyper-expanse/npm-publish-git-tag
  script:
    - $(yarn bin)/semantic-release-gitlab
  stage: release

publish:
  <<: [*node_8]
  before_script:
    - yarn install --frozen-lockfile
  only:
    - tags
  script:
    - node ./src/cli.js
